{
  "formatVersion": "1.1",
  "component": {
    "group": "org.rsmod",
    "module": "rsmod-extra",
    "version": "1.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "rsmod-extra-1.0.2.jar",
          "url": "rsmod-extra-1.0.2.jar",
          "size": 157698,
          "sha512": "b26ae2b2d69c5887e72c6607aa8784f7260bfb61748f9c5ee8d06ec5b807caf1e824e85cd767ebc33ba4c68b4efeaf73747403c1f66ccf4f88a41352ad3c8180",
          "sha256": "48cdfa9647d8de009c57e5e48f5dc7c09b3bfa28fcb09d82f752d59d97895136",
          "sha1": "d7219f4d410755176d74c998e52c5b7006eb7540",
          "md5": "d01b37fadef2387cbf742494901fc845"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "rsmod-extra-1.0.2.jar",
          "url": "rsmod-extra-1.0.2.jar",
          "size": 157698,
          "sha512": "b26ae2b2d69c5887e72c6607aa8784f7260bfb61748f9c5ee8d06ec5b807caf1e824e85cd767ebc33ba4c68b4efeaf73747403c1f66ccf4f88a41352ad3c8180",
          "sha256": "48cdfa9647d8de009c57e5e48f5dc7c09b3bfa28fcb09d82f752d59d97895136",
          "sha1": "d7219f4d410755176d74c998e52c5b7006eb7540",
          "md5": "d01b37fadef2387cbf742494901fc845"
        }
      ]
    }
  ]
}
